### Get HomePage
GET http://localhost:8080/

### Get all Users
GET http://localhost:8080/user

###
POST http://localhost:8080/user 
Content-Type: application/json

{
	"email": "test@test.test",
	"password": "1234"
}

###
POST http://localhost:8080/user 
Content-Type: application/json

{
	"email": "{{$randomInt 1 10000}}@test.test",
	"password": "1234"
}

### Get all ChatRooms
GET http://localhost:8080/room

### Create ChatRoom
POST http://localhost:8080/room

### Add User to ChatRoom
POST http://localhost:8080/room/1/user
Content-Type: application/json

{
	"userId": "1"
}
